# Generated by Django 2.0.3 on 2018-04-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_number', models.IntegerField()),
                ('voter_status', models.CharField(max_length=10)),
                ('date_registered', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField()),
                ('locality', models.CharField(max_length=50)),
                ('precinct', models.CharField(max_length=20)),
                ('precinct_id', models.IntegerField()),
                ('voted_for_Curr', models.BooleanField()),
            ],
        ),
    ]
