# Generated by Django 2.0.3 on 2018-04-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180401_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='voted_for_Curr',
            new_name='voted',
        ),
    ]
